In [78]:
# %%
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [79]:
# %%
anonymous_data = pd.read_csv('symtomps_disease.csv')
anonymous_data.head()

id     s1           s2                  s3                s4   disease
0   1  fever     swelling               lumps  persistent_sores    cancer
1   2  fever  weight_loss  change_in_appetite       dehydration  diabetes
2   3  fever     lethargy            diarrhea  loss_of_appetite     parvo
3   4  fever  weight_loss  change_in_appetite       dehydration  diabetes
4   5  fever  weight_loss  change_in_appetite       dehydration  diabetes

In [80]:
# %%
anonymous_data.tail()

id      s1           s2              s3          s4 disease
78  79  nausea  foamy_mouth  hypersensitive  restleness  rabies
79  80  nausea  foamy_mouth  hypersensitive  restleness  rabies
80  81  nausea  foamy_mouth  hypersensitive  restleness  rabies
81  82  nausea  foamy_mouth  hypersensitive  restleness  rabies
82  83  nausea  foamy_mouth  hypersensitive  restleness  rabies

In [81]:
# %%
anonymous_data.dtypes

id          int64
s1         object
s2         object
s3         object
s4         object
disease    object
dtype: object

In [82]:
# %%
anonymous_data['s1'].unique()

array(['fever', 'vomiting', 'skin_infection', 'nausea', 'listleness',
       'bad_breath', 'refuse_eat_dryfood', 'ear_canal_redness',
       'diff_pain_urinating', 'weight_loss'], dtype=object)

In [83]:
anonymous_data['s2'].unique()

array(['swelling', 'weight_loss', 'lethargy', 'foamy_mouth',
       'nasal_discharge', 'loose_teeth', 'bad_breath', 'scabs_around_ear',
       'inc_freq_urination', 'anemia', 'enlarged_lymph_nodes',
       'listleness'], dtype=object)

In [84]:
anonymous_data['s3'].unique()

array(['lumps', 'change_in_appetite', 'diarrhea', 'hypersensitive',
       'vomiting', 'honking_sound', 'refuse_eat_dryfood',
       'mouth_blood_discharge', 'hair_loss_around_ear', 'blood_in_urine',
       'gingivitis', 'jaundice', 'coughing'], dtype=object)

In [85]:
anonymous_data['s4'].unique()

array(['persistent_sores', 'dehydration', 'loss_of_appetite',
       'restleness', 'aggression', 'coughing', 'gagging',
       'mouth_blood_discharge', 'loose_teeth', 'balance_issues',
       'excessive_licking_genital_area', 'stomatitis', 'Abcesses',
       'vomiting'], dtype=object)

In [86]:
# %%
anonymous_data['disease'].unique()

array(['cancer', 'diabetes', 'parvo', 'rabies', 'heartworm',
       'kennel_cough', 'dental', 'ear_infection', 'FLUTD', 'FIV', 'FeIV'],
      dtype=object)

In [87]:
# %%
OHE =OneHotEncoder()
print(OHE)

OneHotEncoder()


In [88]:
# %%
OHE.fit_transform(anonymous_data[['s1', 'disease']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [89]:
OHE.fit_transform(anonymous_data[['s2', 'disease']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [90]:
OHE.fit_transform(anonymous_data[['s3', 'disease']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [91]:
OHE.fit_transform(anonymous_data[['s4', 'disease']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [92]:
f_array = OHE.fit_transform(anonymous_data[['s1','s2','s3','s4', 'disease']]).toarray()
OHE.categories_

[array(['bad_breath', 'diff_pain_urinating', 'ear_canal_redness', 'fever',
        'listleness', 'nausea', 'refuse_eat_dryfood', 'skin_infection',
        'vomiting', 'weight_loss'], dtype=object),
 array(['anemia', 'bad_breath', 'enlarged_lymph_nodes', 'foamy_mouth',
        'inc_freq_urination', 'lethargy', 'listleness', 'loose_teeth',
        'nasal_discharge', 'scabs_around_ear', 'swelling', 'weight_loss'],
       dtype=object),
 array(['blood_in_urine', 'change_in_appetite', 'coughing', 'diarrhea',
        'gingivitis', 'hair_loss_around_ear', 'honking_sound',
        'hypersensitive', 'jaundice', 'lumps', 'mouth_blood_discharge',
        'refuse_eat_dryfood', 'vomiting'], dtype=object),
 array(['Abcesses', 'aggression', 'balance_issues', 'coughing',
        'dehydration', 'excessive_licking_genital_area', 'gagging',
        'loose_teeth', 'loss_of_appetite', 'mouth_blood_discharge',
        'persistent_sores', 'restleness', 'stomatitis', 'vomiting'],
       dtype=object),
 array(

In [93]:
# %%

f_labels = OHE.categories_

In [94]:
# %%
np.array(f_labels).ravel()

C:\Users\Danil Jeus Ampatin\AppData\Local\Temp\ipykernel_13948\2535540723.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(f_labels).ravel()


array([array(['bad_breath', 'diff_pain_urinating', 'ear_canal_redness', 'fever',
              'listleness', 'nausea', 'refuse_eat_dryfood', 'skin_infection',
              'vomiting', 'weight_loss'], dtype=object)                         ,
       array(['anemia', 'bad_breath', 'enlarged_lymph_nodes', 'foamy_mouth',
              'inc_freq_urination', 'lethargy', 'listleness', 'loose_teeth',
              'nasal_discharge', 'scabs_around_ear', 'swelling', 'weight_loss'],
             dtype=object)                                                      ,
       array(['blood_in_urine', 'change_in_appetite', 'coughing', 'diarrhea',
              'gingivitis', 'hair_loss_around_ear', 'honking_sound',
              'hypersensitive', 'jaundice', 'lumps', 'mouth_blood_discharge',
              'refuse_eat_dryfood', 'vomiting'], dtype=object)               ,
       array(['Abcesses', 'aggression', 'balance_issues', 'coughing',
              'dehydration', 'excessive_licking_genital_area', 'gagg

In [95]:
# %%
f_labels = np.array(f_labels).ravel()
print(f_labels)

[array(['bad_breath', 'diff_pain_urinating', 'ear_canal_redness', 'fever',
        'listleness', 'nausea', 'refuse_eat_dryfood', 'skin_infection',
        'vomiting', 'weight_loss'], dtype=object)
 array(['anemia', 'bad_breath', 'enlarged_lymph_nodes', 'foamy_mouth',
        'inc_freq_urination', 'lethargy', 'listleness', 'loose_teeth',
        'nasal_discharge', 'scabs_around_ear', 'swelling', 'weight_loss'],
       dtype=object)
 array(['blood_in_urine', 'change_in_appetite', 'coughing', 'diarrhea',
        'gingivitis', 'hair_loss_around_ear', 'honking_sound',
        'hypersensitive', 'jaundice', 'lumps', 'mouth_blood_discharge',
        'refuse_eat_dryfood', 'vomiting'], dtype=object)
 array(['Abcesses', 'aggression', 'balance_issues', 'coughing',
        'dehydration', 'excessive_licking_genital_area', 'gagging',
        'loose_teeth', 'loss_of_appetite', 'mouth_blood_discharge',
        'persistent_sores', 'restleness', 'stomatitis', 'vomiting'],
       dtype=object)
 array(['FI

C:\Users\Danil Jeus Ampatin\AppData\Local\Temp\ipykernel_13948\373947979.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  f_labels = np.array(f_labels).ravel()


In [96]:
# %%
pd.DataFrame(f_array,columns=f_labels)

TypeError: __init__() got an unexpected keyword argument 'cols'

In [ ]:
# %%
features = pd.DataFrame(f_array,columns=f_labels)

print(features)

ValueError: Shape of passed values is (83, 60), indices imply (83, 5)

In [ ]:
# %%
features.head()

NameError: name 'features' is not defined

In [ ]:
# %%
features.tail()

NameError: name 'features' is not defined

In [ ]:
# %%
pd.concat([anonymous_data, features], axis=1)

In [ ]:
# %%
anonymous_data_new_dataset = pd.concat([anonymous_data, features], axis=1)

In [ ]:
anonymous_data_new_dataset.head()